/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Inheritance;

public class Library {

    public static void main(String[] args){
        System.out.println("Library Class");
        Restaurant resturant1 = new Restaurant("Ali Akef" , 5 , 50);
        System.out.println(resturant1);
        }
}
