/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/*
*
* */

public class LibraryTest {

    @Test public void addReviewTest(){
        Review rev1 = new Restaurant("good","Judy",0);
        Restaurant reviewCasting = (Restaurant) rev1;
        reviewCasting.setName("Zanjabeel");
        assertEquals ("{Zanjabeel=[Judy, good, 0]}","{"+reviewCasting.getName()+"=["+reviewCasting.getbody()+", "+reviewCasting.getauthor()+", "+reviewCasting.getStar()+"]}");
    }
    @Test public void testtoStringResturant() {
        Restaurant resturantTest = new Restaurant("Excelent","mahmood",4);
        resturantTest.setName("shawrma of Street");
        resturantTest.setStar(4);
        resturantTest.setPrice(35);
        assertEquals("the Customers "+resturantTest.getauthor() + " voted " +resturantTest.getStar() +" stars " + resturantTest.getbody() , resturantTest.tostring());
    }

}
