/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.*;
import java.nio.Buffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        fixedError();
    }
    public static void fixedError(){
        Path file = Paths.get("C:\\Users\\Dell\\401\\java-fundamentals\\linter\\src\\main\\resources\\gates.js");
        try (InputStream in = Files.newInputStream(file);
             BufferedReader readerFile = new BufferedReader(new InputStreamReader(in))) {
            String textLine;
            StringBuilder codeReformat = new StringBuilder();
            for (int i = 1; (textLine = readerFile.readLine()) != null; i++) {
                if (((!textLine.endsWith(";"))  && (!textLine.endsWith("{")) && (!textLine.endsWith("}")) && (!textLine.contains("if")) && (!textLine.contains("else")))) {
                    System.out.println("Missing Semicolon at Line: " + i);
                    codeReformat.append(textLine).append(";\n");
                } else {
                    System.out.println(textLine);
                }
            }
//            System.out.println("\n\nCode after reformat \n\n"+codeReformat);
        } catch (IOException err) {
            System.err.println(err);
        }

    }
}
